project_id = "jmjreqzgkruanmwswutm"

[functions.farmer-chatbot]
verify_jwt = true

[functions.weather-forecast]
verify_jwt = true

[functions.detect-disease]
verify_jwt = true

[functions.fetch-market-prices]
verify_jwt = false

[functions.fetch-news]
verify_jwt = false